INSERT INTO public."SkillCategory" (id,description,title,"deletedAt","deletedBy",status,"updatedAt","promptFormat","promptIntro","promptTemperature") VALUES
	 ('89182d64-c64e-49b0-91bd-5c35d8dc8335','Teste','Teste','2025-07-02 14:36:12.531','unknown','deleted','2025-07-02 14:36:12.532',NULL,NULL,NULL),
	 ('383d4f4b-560a-4d37-a2ec-fc7c6475da70','A TCC é uma abordagem estruturada, orientada para a ação e para metas, na qual definir objetivos e tarefas de forma colaborativa desde o início fortalece a aliança terapêutica, alinha expectativas e cria um plano de tratamento personalizado. ','2. Estabelecer Objetivos do Tratamento',NULL,NULL,'active','2025-10-13 18:28:33.522',NULL,NULL,NULL),
	 ('20ed4136-8418-4798-ba52-8491a00cd714','Negociar a agenda de uma sessão é uma habilidade essencial que ajuda a iniciar a sessão com o pé direito, esclarece as expectativas para o encontro e promove a colaboração contínua em objetivos e tarefas específicas.','Negociando a Agenda da Sessão','2025-08-04 19:02:06.405','unknown','deleted','2025-08-04 19:02:06.406',NULL,NULL,NULL),
	 ('557fe3e8-84d0-4803-9fd0-7ef4e591e595','Na Terapia Cognitivo-Comportamental (TCC), as emoções são sempre relevantes, mas tornam-se ainda mais centrais em estratégias que buscam evocar e trabalhar a aceitação de emoções difíceis, como acontece nos exercícios de exposição. Nessas situações, o terapeuta deve considerar que a fala do cliente provavelmente surge em um contexto de prática intencional para provocar emoções intensas — seja em uma exposição, indução de humor ou experimento comportamental. Isso pode ocorrer tanto na preparação quanto durante a atividade. Por essa razão, a maior parte dos exemplos de falas de clientes, desde os mais básicos até os mais avançados, foi construída tendo em vista esse cenário de prática clínica.','7. Trabalhando com emoções','2025-09-05 15:58:46.207','unknown','deleted','2025-09-05 15:58:46.208',NULL,NULL,NULL),
	 ('b1f9d512-3700-4927-8ebd-20ca703fe485','Essas atividades facilitam o processo de aprendizado corretivo — tanto durante quanto fora das sessões. Além disso, o trabalho realizado fora das sessões ajuda na na generalização das habilidades e no processo de o cliente tornar-se seu próprio terapeuta.','4. Atribuição e Revisão de "Tarefas de Casa" entre Sessões',NULL,NULL,'active','2025-10-13 18:29:07.819',NULL,NULL,NULL),
	 ('5102db3b-0aaa-4302-be36-ca7e77c88aed','Essas atividades facilitam o processo de aprendizado corretivo — tanto durante quanto fora das sessões. Além disso, o trabalho realizado fora das sessões ajuda na na generalização das habilidades e no processo de o cliente tornar-se seu próprio terapeuta.','Atribuição e Revisão de "Tarefas de Casa" entre Sessões','2025-08-05 14:01:51.069','unknown','deleted','2025-08-05 14:01:51.07',NULL,NULL,NULL),
	 ('c252f8f3-21cf-411f-80e1-aa14a32f3ba4','O trabalho em análise comportamental apoia-se nos princípios do condicionamento clássico e operante, resultando em um repertório de estratégias diversificadas. As intervenções podem ter como foco os antecedentes, o comportamento em si (incluindo possíveis déficits de habilidades), as contingências ou as consequências, de acordo com as características do problema apresentado. Entre as técnicas utilizadas estão a exposição, o controle de estímulos, a programação de atividades, o manejo de contingências e o treinamento de habilidades, entre outras. A escolha tanto do alvo comportamental quanto da intervenção mais adequada pode variar amplamente entre diferentes clientes.','6. Trabalhando com mudanças comportamentais',NULL,NULL,'active','2025-10-13 18:27:48.385','
Responda **exclusivamente** com JSON puro, sem formatação, sem blocos de código e sem explicações externas. Use estritamente o formato:
{
"isValid": boolean, 
"score": number, 
"feedback": "texto breve, gentil e profissional"
}
','Você é um psicólogo especializado em Terapia Cognitivo-Comportamental (TCC) e está atuando como treinador de outros psicólogos. 
Sua tarefa é avaliar se a resposta de terapeuta cumpre todos os critérios técnicos esperados para aquela habilidade que está sendo treinada e caso a resposta não esteja correta, orientá-lo sobre como atingir os critérios esperados.
A avaliação deve seguir os critérios fornecidos pelo usuário. 
Só considere a resposta válida se **TODOS** os critérios forem integralmente atendidos. 
Respostas **metalinguísticas, de teste, ou que não se dirigem ao paciente** devem ser classificadas com inválidas. 
Seja técnico, imparcial e preciso.',4),
	 ('8d1276e5-3161-4da6-9006-9a184a7d2d98','teste2','teste 2','2025-10-09 14:00:46.166','unknown','deleted','2025-10-09 14:00:46.167',NULL,NULL,NULL),
	 ('24f44eeb-bb97-48de-a48d-a1a8a83a8656','teste','teste','2025-10-09 14:00:56.199','unknown','deleted','2025-10-09 14:00:56.2',NULL,NULL,NULL),
	 ('c3736c7f-ef80-4b8d-8af7-5b351529db4b','No espírito do empirismo colaborativo, a descoberta guiada envolve ajudar os clientes a reunir informações relevantes, examiná-las de diferentes maneiras (sem julgamento do
terapeuta) e desenvolver um plano personalizado sobre o que fazer com elas. Em outras palavras, o objetivo de trabalhar com cognições não é simplesmente dizer aos clientes para pensarem diferente ou apontar falhas; em vez disso, é ensinar aos clientes um processo para avaliar sua própria experiência e determinar ações subsequentes com base nessa autorreflexão. Consistente com as perspectivas mais contemporâneas da TCC sobre o trabalho com cognições, consideramos facilitar a flexibilidade cognitiva do cliente como um objetivo central do trabalho com cognições.','5. Trabalhando com mudanças cognitivas',NULL,NULL,'active','2025-10-13 18:29:21.567',NULL,NULL,NULL);
INSERT INTO public."SkillCategory" (id,description,title,"deletedAt","deletedBy",status,"updatedAt","promptFormat","promptIntro","promptTemperature") VALUES
	 ('09b855f6-85fc-4857-9ab7-c6cf55528f76','Na Terapia Cognitivo-Comportamental (TCC), a expertise no trabalho com as emoções é fundamental porque o manejo emocional eficaz permite que o terapeuta ajude o cliente a reconhecer, nomear e tolerar suas experiências afetivas em vez de evitá-las. Embora a TCC tenha se desenvolvido inicialmente com foco em pensamentos e comportamentos, o avanço da abordagem mostrou que a mudança cognitiva e comportamental só é realmente sustentável quando o paciente aprende a lidar com as emoções difíceis de forma consciente e regulada. Assim, a competência emocional do terapeuta — ao acolher, validar e explorar o afeto com segurança — se torna essencial para promover insight, reduzir esquivas e favorecer a aprendizagem emocional corretiva que está no cerne da mudança terapêutica.','7. Trabalhando com Emoções',NULL,NULL,'active','2025-10-31 13:11:36.599',NULL,NULL,NULL),
	 ('a9fd3bb1-0eb8-45b2-9db9-5a76002ffaa6','Negociar a agenda de uma sessão é uma habilidade essencial que ajuda a iniciar a sessão com o pé direito, esclarece as expectativas para o encontro e promove a colaboração contínua em objetivos e tarefas específicas.','3. Negociando a Agenda da Sessão',NULL,NULL,'active','2025-10-13 18:28:52.996',NULL,NULL,NULL),
	 ('dbc4f700-7054-4ade-aaeb-f30ea5ede426','Aprender como explicar a fundamentação da Terapia Cognitivo-Comportamental (TCC) é essencial porque garante que o paciente compreenda de forma clara, acessível e realista o que pode esperar do processo terapêutico. Uma boa explicação fortalece a aliança terapêutica, reduz inseguranças e equívocos comuns sobre a terapia e promove maior engajamento do paciente nas técnicas propostas. Além disso, permite estabelecer expectativas adequadas quanto ao ritmo e ao impacto das mudanças, favorecendo a adesão ao tratamento e aumentando as chances de melhores resultados clínicos.

O que será avaliado:
- Validar a experiência do paciente
- Explicar brevemente como a TCC funciona no tratamento psicológico
- Promover esperança quanto ao uso eficaz da TCC.
- Estabelecer expectativas adequadas sobre a natureza e o impacto da TCC.','1. Explicar a Fundamentação do Tratamento com Terapia Cognitivo-Comportamental',NULL,NULL,'active','2025-10-31 13:11:12.474','Responda exclusivamente com JSON puro, sem formatação, sem blocos de código e sem explicações externas. Use estritamente o formato:{"isValid": boolean, "score": number, "feedback": "texto breve, gentil e profissional"}','Você é um psicólogo especializado em Terapia Cognitivo-Comportamental (TCC) que atua como supervisor técnico e treinador de outros terapeutas. Sua tarefa é avaliar se a resposta de terapeuta cumpre todos os critérios técnicos esperados e orientá-lo como atingir a resposta esperada, se for o caso. A avaliação deve seguir os critérios fornecidos pelo usuário e considerar as variabilidades individuais. Só considere a resposta válida se TODOS os critérios forem integralmente atendidos.  Respostas metalinguísticas, de teste, ou que não se dirigem ao paciente devem ser classificadas falsas. Seja técnico, imparcial, preciso e acolhedor.',4);
